"""29_5_2022_decoupled_test_category_and_lab_test

Revision ID: 05e7bcfb2ade
Revises: 09cc1a576448
Create Date: 2022-05-29 23:39:31.729430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e7bcfb2ade'
down_revision = '09cc1a576448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_test', sa.Column('test_category_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_lab_test_test_category_id'), 'lab_test', ['test_category_id'], unique=False)
    op.drop_constraint('lab_test_test_category_id_fkey', 'lab_test', type_='foreignkey')
    t_test_category = sa.Table("test_category", sa.MetaData(), sa.Column('id', sa.Integer()), sa.Column('name', sa.String()))
    t_lab_test = sa.Table("lab_test", sa.MetaData(),sa.Column("id", sa.Integer(), nullable=False),sa.Column("name", sa.String(), nullable=False),sa.Column("test_category_id", sa.Integer(), nullable=True),sa.Column("test_category_name", sa.String(), nullable=True))
    connection = op.get_bind()
    test_category_results = connection.execute(sa.select([t_test_category.c.id,t_test_category.c.name])).fetchall()
    lab_test_results = connection.execute(sa.select([t_lab_test.c.id,t_lab_test.c.name,t_lab_test.c.test_category_id])).fetchall()
    for lab_test_result in lab_test_results:
        for test_category_result in test_category_results:
            if lab_test_result[2] == test_category_result[0]:
                connection.execute(t_lab_test.update().where(t_lab_test.c.id == lab_test_result[0]).values(test_category_name=test_category_result[1]))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lab_test_test_category_id_fkey', 'lab_test', 'test_category', ['test_category_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lab_test_test_category_id'), table_name='lab_test')
    op.drop_column('lab_test', 'test_category_name')
    # ### end Alembic commands ###
