"""23_5_2022_changed_upper_limit_lower_limit_to_float

Revision ID: 09cc1a576448
Revises: ac9208745950
Create Date: 2022-05-24 00:29:03.016086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cc1a576448'
down_revision = 'ac9208745950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="parameter_range",
        column_name="upper_limit",
        type_=sa.Float(),
    )
    op.alter_column(
        table_name="parameter_range",
        column_name="lower_limit",
        type_=sa.Float(),
    )
    op.alter_column(
        table_name="lab_result",
        column_name="upper_limit",
        type_=sa.Float(),
    )
    op.alter_column(
        table_name="lab_result",
        column_name="lower_limit",
        type_=sa.Float(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="parameter_range",
        column_name="upper_limit",
        type_=sa.Integer(),
    )
    op.alter_column(
        table_name="parameter_range",
        column_name="lower_limit",
        type_=sa.Integer(),
    )
    op.alter_column(
        table_name="lab_result",
        column_name="upper_limit",
        type_=sa.Integer(),
    )
    op.alter_column(
        table_name="lab_result",
        column_name="lower_limit",
        type_=sa.Integer(),
    )
    # ### end Alembic commands ###
