"""1_5_2022

Revision ID: 8246b8c28148
Revises: 963b59de9be8
Create Date: 2022-05-01 17:34:16.119029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8246b8c28148'
down_revision = '963b59de9be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_result', sa.Column('test_name', sa.String(), nullable=True))
    op.add_column('parameter', sa.Column('result_type', sa.Enum('text', 'number', name='result_type_enum'), nullable=True))
    op.add_column('parameter', sa.Column('result_default_text', sa.JSON(), nullable=True))
    op.add_column('parameter_range', sa.Column('low_remark', sa.String(), nullable=True))
    op.add_column('parameter_range', sa.Column('high_remark', sa.String(), nullable=True))
    op.add_column('parameter_range', sa.Column('normal_remark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameter_range', 'normal_remark')
    op.drop_column('parameter_range', 'high_remark')
    op.drop_column('parameter_range', 'low_remark')
    op.drop_column('parameter', 'result_default_text')
    op.drop_column('parameter', 'result_type')
    op.drop_column('lab_result', 'test_name')
    # ### end Alembic commands ###
