"""12_5_2022_fixed_wrong_column_name

Revision ID: ac9208745950
Revises: e6e639fad637
Create Date: 2022-05-12 11:32:01.459244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9208745950'
down_revision = 'e6e639fad637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('sample_id', sa.Integer(), nullable=True))
    op.drop_column('lab_report', 'smaple_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('smaple_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('lab_report', 'sample_id')
    # ### end Alembic commands ###
