"""1_6_2022_add_show_in_request_form_and_report_form

Revision ID: b87307a685fb
Revises: 05e7bcfb2ade
Create Date: 2022-06-01 00:57:29.040952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87307a685fb'
down_revision = '05e7bcfb2ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_test', sa.Column('show_in_request_form', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('lab_test', sa.Column('show_in_report_form', sa.Boolean(), server_default='false', nullable=True))
    t_lab_test = sa.Table("lab_test", sa.MetaData(),sa.Column("id", sa.Integer(), nullable=False),sa.Column("name", sa.String(), nullable=False),sa.Column("test_category_id", sa.Integer(), nullable=True),sa.Column("test_category_name", sa.String(), nullable=True),sa.Column("show_in_request_form", sa.Boolean(), server_default='false', nullable=True),sa.Column("show_in_report_form", sa.Boolean(), server_default='false', nullable=True))
    t_parameter = sa.Table("parameter", sa.MetaData(),sa.Column("id", sa.Integer(), nullable=False),sa.Column("name", sa.String(), nullable=False),sa.Column("lab_test_id", sa.Integer(), nullable=True),sa.Column("lab_test_name", sa.String(), nullable=True))
    connection = op.get_bind()
    lab_test_results = connection.execute(sa.select([t_lab_test.c.id,t_lab_test.c.name,t_lab_test.c.test_category_id])).fetchall()
    for lab_test_result in lab_test_results:
        p = connection.execute(sa.select([t_parameter.c.id]).where(t_parameter.c.lab_test_id == lab_test_result[0])).fetchall()
        if len(p) > 1:
            connection.execute(t_lab_test.update().where(t_lab_test.c.id == lab_test_result[0]).values(show_in_request_form=True,show_in_report_form=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_test', 'show_in_report_form')
    op.drop_column('lab_test', 'show_in_request_form')
    # ### end Alembic commands ###
