"""9_7_2022_added_patient_id_field

Revision ID: bce82a304e66
Revises: d0e0509cd74b
Create Date: 2022-07-09 12:24:16.962599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce82a304e66'
down_revision = 'd0e0509cd74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('patient_id', sa.String(), nullable=True))
    op.alter_column(
        table_name="patient",
        column_name="age",
        type_=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'patient_id')
    op.alter_column(
        table_name="patient",
        column_name="age",
        type_=sa.Integer(),
    )
    # ### end Alembic commands ###
