"""10_5_2022_added_cascade_to_test_category

Revision ID: e6e639fad637
Revises: d4b634d994d7
Create Date: 2022-05-10 01:41:59.120582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e639fad637'
down_revision = 'd4b634d994d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lab_test_test_category_id_fkey', 'lab_test', type_='foreignkey')
    op.create_foreign_key(None, 'lab_test', 'test_category', ['test_category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parameter_lab_test_id_fkey', 'parameter', type_='foreignkey')
    op.create_foreign_key(None, 'parameter', 'lab_test', ['lab_test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parameter_range_parameter_id_fkey', 'parameter_range', type_='foreignkey')
    op.create_foreign_key(None, 'parameter_range', 'parameter', ['parameter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parameter_range', type_='foreignkey')
    op.create_foreign_key('parameter_range_parameter_id_fkey', 'parameter_range', 'parameter', ['parameter_id'], ['id'])
    op.drop_constraint(None, 'parameter', type_='foreignkey')
    op.create_foreign_key('parameter_lab_test_id_fkey', 'parameter', 'lab_test', ['lab_test_id'], ['id'])
    op.drop_constraint(None, 'lab_test', type_='foreignkey')
    op.create_foreign_key('lab_test_test_category_id_fkey', 'lab_test', 'test_category', ['test_category_id'], ['id'])
    # ### end Alembic commands ###
